---
title: "Vision_RSFC_Psychosis"
author: "Yiming Qian"
date: "2026-02-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Description

This is a R Markdown code for the manuscript: .
The codes have mainly four part: Geting the data and clean-up, Data Imputation, mediation models, visualization. I wrote the codes for Data Imputation and mediation models. Jeff, please fill the cleaning-up and change the variable names if needed.

## Getting the variables and clean-up
Get the variables required. The key variables include: childhood adversity items, 5 vision-network functional connectivity metrics, 3 auditory-network functional connectivity metrics, PLEs score, PLEs visual distortion score and PLEs auditory score, and covariates. The covariates include 
Clean and organize the data based on the description in the registered report. The step include checking the outliers and rename the variables.


## Imputation
In the registered report, we mentioned we want to do FIML. However, it is no straightforward way to do FIML in the current mediation models in R package. Thus, we do the imputation first.

## mediation models

### mediation models

### moderated mediation models

## Visualization

